[build]
  command = "pip install -r requirements.txt && mkdir -p static/static && cp -r app/static/* static/static/ && cp app/templates/index.html static/"
  publish = "static"
  functions = "netlify/functions"

[build.environment]
  PYTHON_VERSION = "3.12"
  NODE_VERSION = "16"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/static/*"
  to = "/static/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200