[build]
  command = "ls -la && pwd && pip install pipenv && pipenv --version && python --version && mkdir -p static/templates static/static && npm run build"
  publish = "static"
  functions = "netlify/functions"

[build.environment]
  PYTHON_VERSION = "3.12"
  NODE_VERSION = "16"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200