[build]
  command = "pip install -r requirements.txt && mkdir -p static/templates static/static && cp -r app/templates/* static/templates/ && cp -r app/static/* static/"
  publish = "static"
  functions = "netlify/functions"

[build.environment]
  PYTHON_VERSION = "3.12"
  NODE_VERSION = "16"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200